[package]
name = "serde_flatten_enum"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { path = "../serde/serde" }
serde_derive = { path = "../serde/serde_derive" }

[dev-dependencies]
serde_json = "1.0.96"

[patch.crates-io]
serde = { path = "../serde/serde" }